INSERT INTO capstone_pref_course (cpc_id, cpc_code, cpc_name) VALUES  
    (1, 'CS261', 'Data Structures'), 
    (2, 'CS271', 'Computer Architecture and Assembly Language'), 
    (3, 'CS290', 'Web Development'), 
    (4, 'CS312', 'System Administration'), 
    (5, 'CS325', 'Analysis of Algorithms'), 
    (6, 'CS331', 'Introduction to Artificial Intelligence'), 
    (7, 'CS340', 'Introduction to Databases'),
    (8, 'CS370', 'Introduction to Security'), 
    (9, 'CS427', 'Cryptography'),
    (10, 'CS450', 'Introduction to Computer Graphics'),
    (11, 'CS468', 'Inclusive Design'),
    (12, 'CS492', 'Mobile Software Development'),
    (13, 'ECE271', 'Digital Logic Design'),
    (14, 'ECE351/ECE352', 'Signals and Systems'),
    (15, 'ECE372', 'Introduction to Computer Networks'),
    (16, 'ECE391', 'Transmission Lines'),
    (17, 'ECE411', 'Engineering Magnetics'),
    (18, 'ECE416', 'Electronic Materials and Devices'),
    (19, 'ECE418', 'Semiconductor Devices'),
    (20, 'ECE451', 'Systems Dynamics and Control'),
    (21, 'ECE463', 'Wireless Communications Network');