INSERT INTO `capstone_keyword` (`ck_id`, `ck_name`, `ck_parent_ck_id`, `ck_approved`) VALUES
(NULL, 'C++', NULL, 1),
(NULL, 'C', NULL, 1),
(NULL, 'C#', NULL, 1),
(NULL, 'Java', NULL, 1),
(NULL, 'Javascript', NULL, 1),
(NULL, 'Perl', NULL, 1),
(NULL, 'PHP', NULL, 1),
(NULL, 'Python', NULL, 1),
(NULL, 'Ruby', NULL, 1),
(NULL, 'Python', NULL, 1),
(NULL, '.NET', NULL, 1),
(NULL, 'ASP', NULL, 1),
(NULL, 'Haskell', NULL, 1),
(NULL, 'Web Applications', NULL, 1),
(NULL, 'Machine Learning', NULL, 1),
(NULL, 'Security', NULL, 1),
(NULL, 'SQL', NULL, 1),
(NULL, 'Databases', NULL, 1),
(NULL, 'Client Side', NULL, 1),
(NULL, 'Server Side', NULL, 1),
(NULL, 'Game Development', NULL, 1),
(NULL, 'OpenCV', NULL, 1),
(NULL, 'Computer Vision', NULL, 1),
(NULL, '3D Printing', NULL, 1),
(NULL, 'NODE.js', NULL, 1),
(NULL, 'Linux', NULL, 1),
(NULL, 'Website', NULL, 1),
(NULL, 'Mobile Development', NULL, 1),
(NULL, 'Cloud', NULL, 1),
(NULL, 'Software Engineering', NULL, 1),
(NULL, 'Unity', NULL, 1),
(NULL, 'Unreal Game Engine', NULL, 1),
(NULL, 'Git', NULL, 1),
(NULL, 'Android', NULL, 1),
(NULL, 'iOS', NULL, 1),
(NULL, 'Analog', NULL, 1),
(NULL, 'Project Management', NULL, 1),
(NULL, 'System Design', NULL, 1),
(NULL, 'System Testing', NULL, 1),
(NULL, 'Soldering', NULL, 1),
(NULL, 'Arduino', NULL, 1),
(NULL, 'AVR Microcontrollers', NULL, 1),
(NULL, 'Embedded Systems', NULL, 1),
(NULL, 'PCB', NULL, 1),
(NULL, 'Teensy', NULL, 1),
(NULL, 'Verilog', NULL, 1),
(NULL, 'FPGA', NULL, 1),
(NULL, 'Enclosure', NULL, 1),
(NULL, 'Laser Cutting', NULL, 1),
(NULL, 'Drones', NULL, 1),
(NULL, 'Databases', NULL, 1),
(NULL, 'Research', NULL, 1),
(NULL, 'Virtual Reality', NULL, 1),
(NULL, 'Augmented Reality', NULL, 1),
(NULL, 'Neural Networks', NULL, 1),
(NULL, 'Visual Studio', NULL, 1),
(NULL, 'Full Stack', NULL, 1),
(NULL, 'Data Mining', NULL, 1),
(NULL, 'Artificial Intelligence', NULL, 1),
(NULL, 'Voice Recognition', NULL, 1),
(NULL, 'Robotics', NULL, 1),
(NULL, 'Microservices', NULL, 1),
(NULL, 'Algorithms', NULL, 1),
(NULL, 'Usability', NULL, 1),
(NULL, 'Education', NULL, 1),
(NULL, 'Automation', NULL, 1),
(NULL, 'Internship', NULL, 1),
(NULL, 'Computation', NULL, 1),
(NULL, 'Matlab', NULL, 1),
(NULL, 'Prolog', NULL, 1),
(NULL, 'Visual Basic', NULL, 1),
(NULL, 'Open Source', NULL, 1),
(NULL, 'Computer Architecture', NULL, 1),
(NULL, 'Operating Systems', NULL, 1),
(NULL, 'HTML', NULL, 1),
(NULL, 'CSS', NULL, 1),
(NULL, 'Atom', NULL, 1),
(NULL, 'Sublime', NULL, 1),
(NULL, 'Communication', NULL, 1),
(NULL, 'Eclipse', NULL, 1),
(NULL, 'Hardware Verification', NULL, 1),
(NULL, 'Documentation', NULL, 1),
(NULL, 'Technical Writing', NULL, 1),
(NULL, 'BeagleBone', NULL, 1),
(NULL, 'Accelerometer', NULL, 1),
(NULL, 'Solar Panel', NULL, 1),
(NULL, 'Programmable Logic Controller', NULL, 1),
(NULL, 'Hardware', NULL, 1),
(NULL, 'API', NULL, 1),
(NULL, 'Agile', NULL, 1),
(NULL, 'Waterfall', NULL, 1),
(NULL, 'R', NULL, 1),
(NULL, 'Swift', NULL, 1),
(NULL, 'Objective-C', NULL, 1),
(NULL, 'Assembly', NULL, 1),
(NULL, 'Delphi', NULL, 1),
(NULL, 'Go', NULL, 1),
(NULL, 'Scratch', NULL, 1),
(NULL, 'Problem Solving', NULL, 1),
(NULL, 'Erlang', NULL, 1),
(NULL, 'XML', NULL, 1),
(NULL, 'Kubernetes', NULL, 1);
