SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS capstone_application_review;
DROP TABLE IF EXISTS capstone_application;
DROP TABLE IF EXISTS capstone_application_status;
DROP TABLE IF EXISTS capstone_interest_level;
DROP TABLE IF EXISTS capstone_category;
DROP TABLE IF EXISTS capstone_category_for;
DROP TABLE IF EXISTS capstone_keyword;
DROP TABLE IF EXISTS capstone_keyword_for;
DROP TABLE IF EXISTS capstone_pref_course;
DROP TABLE IF EXISTS capstone_pref_course_for;
DROP TABLE IF EXISTS capstone_project_edit_permissions;
SET FOREIGN_KEY_CHECKS = 1;
